# Generated by Django 4.0.6 on 2022-08-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueat', '0003_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_cat', models.CharField(max_length=500)),
            ],
        ),
    ]
