# Generated by Django 4.0.6 on 2022-08-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueat', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='prod_img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
