# Generated by Django 4.0.6 on 2022-08-10 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ueat', '0005_product_category_prod_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_category',
            old_name='prod_cat',
            new_name='prod_subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ueat.product_category'),
        ),
    ]
