# Generated by Django 4.0.6 on 2022-08-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueat', '0006_rename_prod_cat_product_category_prod_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.CharField(max_length=100),
        ),
    ]
