# Generated by Django 4.0.6 on 2022-08-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ueat', '0007_alter_product_prod_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='prod_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ueat.product_category'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='prod_subcategory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
