# Generated by Django 4.0.6 on 2022-08-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueat', '0008_product_category_prod_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Product_category',
        ),
    ]
